version: '3'

services:

  bitcored:
    build:
      context: ./docker-bitcored
      dockerfile: ./Dockerfile
    image: bitcored
    container_name: bitcored
    command:
      -whitebind=172.21.0.10:8555
      -whitelist=172.21.0.0/24
      -whitelist=127.0.0.1
      -txindex=1
      -addressindex=0
      -timestampindex=0
      -spentindex=0
      -maxconnections=100
      -rpcbind=172.21.0.10
      -rpcallowip=172.21.0.0/24
      -rpcallowip=127.0.0.1
      -port=8555
      -rpcport=8556
      -rpcuser=btx 
      -rpcpassword=btx
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.10
    ports:
      - 8555:8555 
    expose:
      - 8555
      - 8556 
    volumes:
      #- bitcored-storage:/data
      - /home/bitcore:/data

  mongodb:
    image: mongo:3.4-jessie
    container_name: mongodb
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.11
    ports: 
      - 27017:27017
    expose:
      - 27017
    volumes:
      #- mongodb-storage:/data/db
      - /home/mongodb:/data/db

  bitcore-node:
    build:
      context: .
      dockerfile: ./Dockerfile.bitcore-node.btx
    image: bitcore-node
    container_name: bitcore-node
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.13 
    ports:
      #- 8100:8100
      - 3000:3000
    expose:
      - 3000
      - 8100
    environment:
      - "DB_HOST=mongodb"
      - "BITCORE_CONFIG_PATH=/bitcore/bitcore.config.json"
    depends_on:
      - mongodb
      - bitcored

  insight:
    image: insight
    build:
      context: ./packages/insight-previous
      dockerfile: ./Dockerfile
    container_name: insight
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.14
    ports:
      - 8100:8100
    expose:
      - 8100
      - 3000
    environment:
      - "ENV=prod"
      - "CHAIN=BTX"
      - "NETWORK=mainnet"
      - "API_PREFIX=https://172.21.0.14/api"
    depends_on:
      - bitcore-node

#volumes:
#  bitcored-storage:
#  mongodb-storage:

networks:
  insight-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

