version: "3"

services:

  test_runner:
    build:
      context: .
      #dockerfile: Dockerfile-test
      dockerfile: Dockerfile
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore-test
      - BITCORE_CONFIG_PATH=/bitcore/bitcore-test_btx.config.json
    depends_on:
      - db
      - btx

  db:
    image: mongo

  btx:
    image: dalijolijo/bitcored:0.15.2.1
    command:
      -printtoconsole
      -regtest=1
      -txindex=0
      -listen=1
      -server=1
      -irc=0
      -upnp=0
      -dnsseed=0
      -port=8555
      -rpcport=8556
      -rpcallowip=172.0.0.0/8
      -rpcbind=0.0.0.0
      -rpcuser=bitcorenodetest
      -rpcpassword=local321

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
